# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2023-07-29 11:01+0330\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: helpers/client_functions.py:75 helpers/client_functions.py:280
#: helpers/client_functions.py:381 helpers/client_functions.py:522
#: helpers/client_functions.py:641 helpers/client_functions.py:678
#: helpers/client_functions.py:740 helpers/client_functions.py:783
#: helpers/client_functions.py:860 helpers/client_functions.py:927
#: helpers/client_functions.py:1066 helpers/client_functions.py:1123
#: helpers/client_functions.py:1208 helpers/client_functions.py:1287
#: helpers/client_functions.py:1384 helpers/client_functions.py:1435
#: helpers/client_functions.py:1651 helpers/client_functions.py:1707
#: helpers/client_functions.py:1752 helpers/client_functions.py:1830
msgid "join_channel"
msgstr "پیش از اینکه بتوانید از خدمات ربات استفاده کنید، باید در کانال‌های زیر عضو شوید!"

#: helpers/client_functions.py:86 helpers/client_functions.py:292
#: helpers/client_functions.py:392 helpers/client_functions.py:531
#: helpers/client_functions.py:688 helpers/client_functions.py:1075
#: helpers/client_functions.py:1132 helpers/client_functions.py:1217
#: helpers/client_functions.py:1296 helpers/client_functions.py:1444
#: helpers/client_functions.py:1761 helpers/client_functions.py:1839
msgid "user_not_found"
msgstr "کاربر پیدا نشد. ربات را از طریق /start دوباره راه‌اندازی کنید"

#: helpers/client_functions.py:147
msgid "no_server_available"
msgstr "متاسفانه سرور بیشتری برای شما در دسترس نیست."

#: helpers/client_functions.py:157 helpers/client_functions.py:314
#: helpers/client_functions.py:440 helpers/client_functions.py:660
#: helpers/client_functions.py:765 helpers/client_functions.py:820
#: helpers/client_functions.py:888 helpers/client_functions.py:943
#: helpers/client_functions.py:994 helpers/client_functions.py:1416
#: helpers/client_functions.py:1679 helpers/client_functions.py:1733
msgid "general_cancel"
msgstr "❌ لغو کردن"

#: helpers/client_functions.py:161 helpers/client_functions.py:419
msgid "select_server"
msgstr "*یک سرور انتخاب کنید*"

#: helpers/client_functions.py:162 helpers/client_functions.py:420
msgid "servers_list"
msgstr "*===== لیست سرورها =====*"

#: helpers/client_functions.py:212
msgid "error_account_creation_api_conflict"
msgstr "Error - Failed to Create Account (Database/API Conflict)"

#: helpers/client_functions.py:224
msgid "error_failed_account_creations"
msgstr "Error - Failed to Create Account"

#: helpers/client_functions.py:231 helpers/client_functions.py:492
msgid "error_get_config_api_conflict"
msgstr "Failed to get your config (API/Database Conflict)"

#: helpers/client_functions.py:235 helpers/client_functions.py:247
msgid "account_ready"
msgstr "کانفیگ شما حاضر است! در نرم‌افزار خود وارد کرده و لذت ببرید!"

#: helpers/client_functions.py:302 helpers/client_functions.py:318
#: helpers/client_functions.py:402 helpers/client_functions.py:540
msgid "get_an_account"
msgstr "شما هنوز هیچ کانفیگی ندارید. ابتدا از ربات حداقل یک کانفیگ بگیرید."

#: helpers/client_functions.py:345
msgid "error_get_account_status"
msgstr "Error - Failed to Get Account Status (Database/API Conflict)"

#: helpers/client_functions.py:351
msgid "unlimited"
msgstr "نامحدود"

#: helpers/client_functions.py:352
msgid "account_status"
msgstr "*===== وضعیت اکانت =====*"

#: helpers/client_functions.py:353
msgid "username"
msgstr "نام‌کاربری"

#: helpers/client_functions.py:354
msgid "server_name"
msgstr "نام سرور"

#: helpers/client_functions.py:355
msgid "active"
msgstr "فعال"

#: helpers/client_functions.py:356
msgid "upload_download"
msgstr "آپلود / دانلود"

#: helpers/client_functions.py:357
msgid "used/limit"
msgstr "استفاده شده / محدودیت"

#: helpers/client_functions.py:485
msgid "refreshed_vmess"
msgstr "کانفیگ شما آماده است"

#: helpers/client_functions.py:539 helpers/client_functions.py:545
#: helpers/client_functions.py:559 helpers/client_functions.py:586
#: helpers/client_functions.py:594
msgid "your_user_id"
msgstr "آی‌دی شما"

#: helpers/client_functions.py:560
msgid "join_org"
msgstr "شما باید عضو یک ارگانیزیشن باشید! برای این منظور لطفاً یک پرداخت انجام دهید."

#: helpers/client_functions.py:587 helpers/client_functions.py:595
msgid "contact_support"
msgstr "لطفاً با پشتیبانی ارتباط بگیرید"

#: helpers/client_functions.py:587 helpers/client_functions.py:595
msgid "error_code"
msgstr "*Error code*"

#: helpers/client_functions.py:615
msgid "usage"
msgstr "مصرف شده"

#: helpers/client_functions.py:616
msgid "usage_limit"
msgstr "محدودیت اکانت"

#: helpers/client_functions.py:657
msgid "send_ticket"
msgstr "لطفاً تیکت خود را ارسال کنید"

#: helpers/client_functions.py:720
msgid "thanks_ticket"
msgstr "سپاس بابت تیکتی که ارسال کردید !🤍️\nبه زودی با شما ارتباط خواهیم گرفت!"

#: helpers/client_functions.py:762
msgid "referal_code"
msgstr "لطفاً *کد معرف* خود را وارد کنید:\nاگر کد معرف ندارید، لطفاً به منو بازگشته و به پشتیبانی یک تیکت ارسال کنید."

#: helpers/client_functions.py:811
msgid "choose_plan"
msgstr "لطفاً یکی از پلن‌های موجود را انتخاب کنید:\nدر نظر داشته باشید که قیمت‌ها ممکن است به علت نوسانات قیمت‌های دلار/ترون/ریال و هزینه‌های تبدیل آن‌ها، نوسان داشته باشند."

#: helpers/client_functions.py:938
msgid "transaction_receipt"
msgstr "لطفاً رسید خرید خود را ارسال کنید"

#: helpers/client_functions.py:938 helpers/client_functions.py:954
#: helpers/client_functions.py:1409 helpers/client_functions.py:1542
#: helpers/client_functions.py:1726
msgid "selected_plan"
msgstr "پلن انتخاب شده"

#: helpers/client_functions.py:940 helpers/client_functions.py:1728
msgid "card_number"
msgstr "شماره کارت"

#  helpers/client_functions.py: 657
#: helpers/client_functions.py:941 helpers/client_functions.py:954
#: helpers/client_functions.py:1412 helpers/client_functions.py:1667
#: helpers/client_functions.py:1729
msgid "cancel_to_abort"
msgstr "برای انصراف، دکمه‌ی لغو کردن را انخاب کنید"

#: helpers/client_functions.py:954
msgid "zarinpal_message"
msgstr "لطفاً از طریق لینک زیر تراکنش خود را انجام دهید"

#: helpers/client_functions.py:993
msgid "pay_now"
msgstr "💰 پرداخت کن"

#: helpers/client_functions.py:1046 helpers/client_functions.py:1048
msgid "not_yet_verified_payment"
msgstr "تراکنش شما هنوز تأیید نشده است.\nلطفاً پرداخت کرده و دوباره تلاش کنید"

#: helpers/client_functions.py:1107 helpers/client_functions.py:1193
#: helpers/client_functions.py:1269 helpers/client_functions.py:1357
#: helpers/client_functions.py:1815 helpers/client_functions.py:1891
msgid "thanks_for_payment"
msgstr "سپاس از پرداخت و انتخاب شما 🤍️\n\nما رسید پرداخت شما را بررسی کرده و به زودی اکانت شما را فعال خواهیم کرد.\n لطفاً در صورتی که این فرایند بیشتر از ۴ ساعت به طول انجامید، با ما ارتباط بگیرید."

#: helpers/client_functions.py:1410
msgid "send_token"
msgstr "لطفاً توکن‌های خود را ارسال کنید به میزان"

#: helpers/client_functions.py:1410
msgid "to_our_wallet"
msgstr "به ولت ما"

#: helpers/client_functions.py:1410
msgid "tron"
msgstr "ترون"

#: helpers/client_functions.py:1411
msgid "crypto_wallet_link"
msgstr "یا پرداخت خود را انجام دهید از طریق"

#: helpers/client_functions.py:1412
msgid "send_transaction_id"
msgstr "در قسمت پایین، *آی‌دی تراکنش* خود را ارسال کنید"

#: helpers/client_functions.py:1493
msgid "verify_crypto_manually"
msgstr "سپاس از خرید و انتخاب شما 🤍️\nاز طریق دکمه‌ی زیر، تراکنش خود را تأیید کنید."

#: helpers/client_functions.py:1497
msgid "verify_crypto_manually2"
msgstr "لطفاً بر روی دکمه‌ی زیر کلیک کرده تا تراکنش شما تأیید شود"

#: helpers/client_functions.py:1501
msgid "check_crypto_button"
msgstr "بررسی وضعیت تراکنش"

#: helpers/client_functions.py:1528
msgid "already_verified_crypto_payment"
msgstr "تراکنش شما قبلاً تأیید شده است!"

#: helpers/client_functions.py:1541
msgid "failed_crypto_transaction"
msgstr "❌ تراکنش شما موفقیت آمیز نبود!"

#: helpers/client_functions.py:1542
msgid "error_wrong_amount"
msgstr "احتمال اشتباه بودن آی‌دی تراکنش وجود دارد."

#: helpers/client_functions.py:1542
msgid "error_wrong_trans_id"
msgstr "احتمال ناهماهنگی و اشتباه بودن میزان توکن یا اشتباه بودن مقصد ولت متناظر با آی‌دی تراکنش ارسالی و پلن انتخاب شده وجود دارد."

#: helpers/client_functions.py:1543
msgid "check_trans_manually_2"
msgstr "شما می‌توانید در اینجا صحت تراکنش خود را بررسی کنید"

#: helpers/client_functions.py:1544
msgid "contact_us_in_advance"
msgstr "اگر همه چیز درست است، لطفاً ما را مطلع کنید"

#: helpers/client_functions.py:1574
msgid "not_verified_payment"
msgstr "تراکنش شما هنوز تأیید نشده است، لطفاً چند دقیقه دیگر دوباره تلاش کنید."

#: helpers/client_functions.py:1605
msgid "verified_account"
msgstr "✅ خرید شما موفقیت آمیز بود!\nاکانت شارژ شد به میزان"

#: helpers/client_functions.py:1606
msgid "added_to_org"
msgstr "شما عضو ارگانیزیشن شدید. لطفاً برای اطلاع از اعلامیه‌های مرتبط با سرورها و کانفیگ‌ها در کانال زیر عضو شوید\nبرای استفاده از قابلیت‌های جدید ربات از طریق /menu در ربات اقدام کنید."

#: helpers/client_functions.py:1606
msgid "group"
msgstr "گروه"

#: helpers/client_functions.py:1667
msgid "choose_plan2"
msgstr "لطفاً یکی از پلن‌های موجود را انتخاب کنید"

#: helpers/client_functions.py:1726
msgid "send_crypto_transaction_receipt"
msgstr "لطفاً رسید تراکنش خود را ارسال کنید"

msgid "GB"
msgstr "گیگ"

msgid "T"
msgstr "تومان"